from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional
import joblib


@dataclass
class PreprocessingData:
    """Data paths generated by PreprocessingStep.
    Regarding if it's the training or inference pipeline, the correct paths need to be implemented
    (respectively train_path, test_path / batch_path)
    """

    train_path: Optional[Path] = None
    test_path: Optional[Path] = None
    batch_path: Optional[Path] = None